### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by cipig** [wetblanketcc/aiostratum_proxy#6]
When i run `aiostratum-proxy --version` i get this error
```
Traceback (most recent call last):
  File "/usr/local/bin/aiostratum-proxy", line 11, in <module>
    load_entry_point('aiostratum-proxy==1.1', 'console_scripts', 'aiostratum-proxy')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/aiostratum_proxy-1.1-py3.7.egg/aiostratum_proxy/__init__.py", line 6, in <module>
AttributeError: 'NoneType' object has no attribute 'replace'
```

I am using Debian 9 and Python 3.7.2+
Also tried another server with Debian 9, but Python 3.5.3 and same error.

**Comment by Kroch** [comment]
HI!
try to change 
__init__.py
this row:
__appname__ = __package__.replace('_', '-')
to
__appname__ = "aiostratum-proxy"

This change works for me (Win7 x64 python 3 7 4 )

**Comment by Kroch** [comment]
I can't use it for BEAM mining ....
Can anyone knows working proxy for BEAM or GRIN coin?
